local colors = {
  bgDark        = "#211D26",
  bgLight       = "#775E7B",
  white         = "#ffffff",
  black         = "#000000",
  red           = "#ff0000",
  green         = "#00ff00",
  blue          = "#0000ff",
  yellow        = "#ffff00",
  magenta       = "#ff00ff",
  cyan          = "#00ffff",
  transparent   = "#000000",
  caret         = "#ffffff",
  selection     = "#000000",
  comment       = "#00ff00",
  constant      = "#ffff00",
  error         = "#ff0000",
  ["function"]  = "#ffff00",
  keyword       = "#ffff00",
  label         = "#ffff00",
  number        = "#ffff00",
  operator      = "#ffff00",
  preprocessor  = "#ffff00",
  string        = "#ffff00",
  type          = "#ffff00",
  variable      = "#ffff00",
  whitespace    = "#ffff00",
}

return colors
